var features = {
        ambientlight: "Ambient Light Events",
        applicationcache: "Application Cache",
        audio: "HTML5 Audio Element",
        batteryapi: "Battery API",
        blobconstructor: "Blob constructor",
        canvas: "Canvas",
        canvastext: "Canvas text",
        contenteditable: "Content Editable",
        contextmenu: "Context menus",
        cookies: "Cookies",
        cors: "Cross-Origin Resource Sharing",
        cryptography: "Web Cryptography",
        customelements: "Custom Elements API",
        customprotocolhandler: "Custom protocol handler",
        customevent: "CustomEvent",
        dart: "Dart",
        dataview: "DataView",
        emoji: "Emoji",
        eventlistener: "Event Listener",
        exiforientation: "EXIF Orientation",
        flash: "Flash",
        forcetouch: "Force Touch Events",
        fullscreen: "Fullscreen API",
        gamepads: "GamePad API",
        geolocation: "Geolocation API",
        hashchange: "Hashchange event",
        hiddenscroll: "Hidden Scrollbar",
        history: "History API",
        htmlimports: "HTML Imports",
        ie8compat: "IE8 compat mode",
        indexeddb: "IndexedDB",
        indexeddbblob: "IndexedDB Blob",
        input: "Input attributes",
        inputsearchevent: "input[search] search event",
        inputtypes: "Form input types",
        intl: "Internationalization API",
        json: "JSON",
        ligatures: "Font Ligatures",
        olreversed: "Reverse Ordered Lists",
        mathml: "MathML",
        mediasource: "Media Source Extensions API",
        messagechannel: "Message Channel",
        notification: "Notification",
        pagevisibility: "Page Visibility API",
        performance: "Navigation Timing API",
        pointerevents: "DOM Pointer Events API",
        pointerlock: "Pointer Lock API",
        postmessage: "postMessage",
        proximity: "Proximity API",
        queryselector: "QuerySelector",
        quotamanagement: "Quota Storage Management API",
        requestanimationframe: "requestAnimationFrame",
        serviceworker: "ServiceWorker API",
        svg: "SVG",
        templatestrings: "Template strings",
        touchevents: "Touch Events",
        typedarrays: "Typed arrays",
        unicoderange: "Unicode Range",
        unicode: "Unicode characters",
        userdata: "IE User Data API",
        vibrate: "Vibration API",
        video: "HTML5 Video",
        vml: "VML",
        webintents: "Web Intents",
        webanimations: "Web Animation API",
        webgl: "WebGL",
        websockets: "WebSockets Support",
        xdomainrequest: "XDomainRequest",
        adownload: "a[download] Attribute",
        audioautoplay: "Audio Autoplay",
        audioloop: "Audio Loop Attribute",
        audiopreload: "Audio Preload",
        webaudio: "Web Audio API",
        lowbattery: "Low Battery Level",
        canvasblending: "canvas blending support",
        todataurljpeg: "canvas.toDataURL type support",
        canvaswinding: "canvas winding support",
        getrandomvalues: "getRandomValues",
        cssall: "cssall",
        cssanimations: "CSS Animations",
        appearance: "Appearance",
        backdropfilter: "Backdrop Filter",
        backgroundblendmode: "CSS Background Blend Mode",
        backgroundcliptext: "CSS Background Clip Text",
        bgpositionshorthand: "Background Position Shorthand",
        bgpositionxy: "Background Position XY",
        bgrepeatspace: "Background Repeat",
        backgroundsize: "Background Size",
        bgsizecover: "Background Size Cover",
        borderimage: "Border Image",
        borderradius: "Border Radius",
        boxdecorationbreak: "Box Decoration Break",
        boxshadow: "Box Shadow",
        boxsizing: "Box Sizing",
        csscalc: "CSS Calc",
        checked: "CSS :checked pseudo-selector",
        csschunit: "CSS Font ch Units",
        csscolumns: "CSS Columns",
        cssgrid: "CSS Grid (old &amp; new)",
        cubicbezierrange: "CSS Cubic Bezier Range",
        customproperties: "CSS Custom Properties",
        displaytable: "CSS Display table",
        ellipsis: "CSS text-overflow ellipsis",
        cssescape: "CSS.escape()",
        cssexunit: "CSS Font ex Units",
        cssfilters: "CSS Filters",
        flexbox: "Flexbox",
        flexboxlegacy: "Flexbox (legacy)",
        flexboxtweener: "Flexbox (tweener)",
        flexwrap: "Flex Line Wrapping",
        focuswithin: "CSS :focus-within pseudo-selector",
        fontdisplay: "Font Display",
        fontface: "@font-face",
        generatedcontent: "CSS Generated Content",
        cssgradients: "CSS Gradients",
        hairline: "CSS Hairline",
        hsla: "CSS HSLA Colors",
        csshyphens: "CSS Hyphens",
        cssinvalid: "CSS :invalid pseudo-class",
        lastchild: "CSS :last-child pseudo-selector",
        cssmask: "CSS Mask",
        mediaqueries: "CSS Media Queries",
        multiplebgs: "CSS Multiple Backgrounds",
        nthchild: "CSS :nth-child pseudo-selector",
        objectfit: "CSS Object Fit",
        opacity: "CSS Opacity",
        overflowscrolling: "CSS Overflow Scrolling",
        csspointerevents: "CSS Pointer Events",
        csspositionsticky: "CSS position: sticky",
        csspseudoanimations: "CSS Generated Content Animations",
        csspseudotransitions: "CSS Generated Content Transitions",
        cssreflections: "CSS Reflections",
        regions: "CSS Regions",
        cssremunit: "CSS Font rem Units",
        cssresize: "CSS UI Resize",
        rgba: "CSS rgba",
        cssscrollbar: "CSS Stylable Scrollbars",
        scrollsnappoints: "Scroll Snap Points",
        shapes: "CSS Shapes",
        siblinggeneral: "CSS general sibling selector",
        subpixelfont: "CSS Subpixel Fonts",
        supports: "CSS Supports",
        target: "CSS :target pseudo-class",
        textalignlast: "CSS text-align-last",
        textdecoration: "CSS textDecoration",
        textshadow: "CSS textshadow",
        csstransforms: "CSS Transforms",
        csstransforms3d: "CSS Transforms 3D",
        csstransformslevel2: "CSS Transforms Level 2",
        preserve3d: "CSS Transform Style preserve-3d",
        csstransitions: "CSS Transitions",
        userselect: "CSS user-select",
        cssvalid: "CSS :valid pseudo-class",
        variablefonts: "Variable Open Type Fonts",
        cssvhunit: "CSS vh unit",
        cssvmaxunit: "CSS vmax unit",
        cssvminunit: "CSS vmin unit",
        cssvwunit: "CSS vw unit",
        willchange: "will-change",
        wrapflow: "CSS wrap-flow",
        classlist: "classList",
        createelementattrs: "createElement with Attributes",
        dataset: "dataset API",
        documentfragment: "Document Fragment",
        hidden: "[hidden] Attribute",
        intersectionobserver: "Intersection Observer",
        microdata: "microdata",
        mutationobserver: "DOM4 MutationObserver",
        passiveeventlisteners: "Passive event listeners",
        bdi: "bdi Element",
        datalistelem: "datalist Element",
        details: "details Element",
        outputelem: "output Element",
        picture: "picture Element",
        progressbar: "progress Element",
        ruby: "ruby, rp, rt Elements",
        template: "Template Tag",
        time: "time Element",
        texttrackapi: "Track element and Timed Text Track",
        unknownelements: "Unknown Elements",
        es5array: "ES5 Array",
        es5date: "ES5 Date",
        es5function: "ES5 Function",
        es5object: "ES5 Object",
        es5: "ES5",
        strictmode: "ES5 Strict Mode",
        es5string: "ES5 String",
        es5syntax: "ES5 Syntax",
        es5undefined: "ES5 Immutable Undefined",
        es6array: "ES6 Array",
        arrow: "ES6 Arrow Functions",
        es6collections: "ES6 Collections",
        contains: "ES5 String.prototype.contains",
        generators: "ES6 Generators",
        es6math: "ES6 Math",
        es6number: "ES6 Number",
        es6object: "ES6 Object",
        promises: "ES6 Promises",
        es6string: "ES6 String",
        devicemotion: "Orientation and Motion Events",
        oninput: "onInput Event",
        filereader: "File API",
        filesystem: "Filesystem API",
        capture: "input[capture] Attribute",
        fileinput: "input[file] Attribute",
        directory: "input[directory] Attribute",
        formattribute: "input[form] Attribute",
        localizednumber: 'input[type="number"] Localization',
        placeholder: "placeholder attribute",
        requestautocomplete: "form#requestAutocomplete()",
        formvalidation: "Form Validation",
        sandbox: "iframe[sandbox] Attribute",
        seamless: "iframe[seamless] Attribute",
        srcdoc: "iframe[srcdoc] Attribute",
        apng: "Animated PNG",
        imgcrossorigin: "Image crossOrigin",
        jpeg2000: "JPEG 2000",
        jpegxr: "JPEG XR (extended range)",
        sizes: "sizes attribute",
        srcset: "srcset attribute",
        webpalpha: "Webp Alpha",
        webpanimation: "Webp Animation",
        webplossless: "Webp Lossless",
        webp: "Webp",
        inputformaction: "input formaction",
        inputformenctype: "input formenctype",
        inputformmethod: "input formmethod",
        inputformnovalidate: "input formnovalidate",
        inputformtarget: "input formtarget",
        hovermq: "Hover Media Query",
        pointermq: "Pointer Media Query",
        beacon: "Beacon API",
        connectioneffectivetype: "Connection Effective Type",
        lowbandwidth: "Low Bandwidth Connection",
        eventsource: "Server Sent Events",
        fetch: "Fetch API",
        xhrresponsetypearraybuffer: "XHR responseType='arraybuffer'",
        xhrresponsetypeblob: "XHR responseType='blob'",
        xhrresponsetypedocument: "XHR responseType='document'",
        xhrresponsetypejson: "XHR responseType='json'",
        xhrresponsetypetext: "XHR responseType='text'",
        xhrresponsetype: "XHR responseType",
        xhr2: "XML HTTP Request Level 2 XHR2",
        scriptasync: "script[async]",
        scriptdefer: "script[defer]",
        speechrecognition: "Speech Recognition API",
        speechsynthesis: "Speech Synthesis API",
        localstorage: "Local Storage",
        sessionstorage: "Session Storage",
        websqldatabase: "Web SQL Database",
        stylescoped: "style[scoped]",
        svgasimg: "SVG as an <img> tag source",
        svgclippaths: "SVG clip paths",
        svgfilters: "SVG filters",
        svgforeignobject: "SVG foreignObject",
        inlinesvg: "Inline SVG",
        smil: "SVG SMIL animation",
        textareamaxlength: "textarea maxlength",
        bloburls: "Blob URLs",
        datauri: "Data URI",
        urlparser: "URL parser",
        urlsearchparams: "URLSearchParams API",
        videoautoplay: "Video Autoplay",
        videocrossorigin: "Video crossOrigin",
        videoloop: "Video Loop Attribute",
        videopreload: "Video Preload Attribute",
        publicKeyCredential: "PublicKeyCredential",
        webglextensions: "WebGL Extensions",
        datachannel: "RTC Data Channel",
        getusermedia: "getUserMedia",
        peerconnection: "RTC Peer Connection",
        websocketsbinary: "Binary WebSockets",
        atobbtoa: "Base 64 encoding/decoding",
        framed: "Framed window",
        matchmedia: "matchMedia",
        blobworkers: "Workers from Blob URIs",
        dataworkers: "Workers from Data URIs",
        sharedworkers: "Shared Workers",
        transferables: "Transferables Objects",
        webworkers: "Web Workers",
};
